import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import { Roster } from "~/components/Roster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <nav className="backdrop-blur bg-stone-950 p-4">
          <Link className="text-white" href="/">Home</Link>
        </nav>
        <main className="min-h-screen bg-stone-950">
          {children}
          <Roster />
        </main>
      </body>
    </html>
  );
}
